# Generated by Django 4.1.6 on 2023-02-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('end_at', models.DateTimeField(auto_now=True, verbose_name='Дата дедлайна')),
            ],
        ),
    ]
