# Generated by Django 4.1.6 on 2023-03-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, null=True, verbose_name='Текст')),
                ('detail_text', models.TextField(max_length=3000, null=True, verbose_name='Детальный текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_at', models.DateTimeField(default=None, null=True, verbose_name='Дата удаления')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='webapp.status', verbose_name='Статус')),
                ('teg', models.ManyToManyField(blank=True, related_name='articles', to='webapp.teg')),
            ],
        ),
    ]
