# Generated by Django 4.1.6 on 2023-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_article_create_at_alter_article_end_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='end_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=3000, null=True, verbose_name='Текст'),
        ),
    ]
